AWSTemplateFormatVersion: 2010-09-09

Resources: 
  IamRoleToAccessS3:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement: 
          - Effect: Allow
            Principal: 
              Service:
                - "ec2.amazonaws.com"
            Action: 
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Tags: 
        - Key: Name
          Value: IamRole-CF
  IamInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref IamRoleToAccessS3

Outputs:
  IamInstanceProfile:
    Value: !Ref IamInstanceProfile
    Export:
      Name: RaiseTechSampleApp-InstanceProfile
